image: docker:latest

services:
- docker:dind

stages:
  - build
  - qa
  - release

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.nanoka.fr/penpals/backend:$CI_BUILD_REF_SLUG
  CONTAINER_RELEASE_IMAGE: registry.gitlab.nanoka.fr/penpals/backend:latest

before_script:
  - apk add --no-cache py2-pip && pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.nanoka.fr
  - docker info

build:
  stage: build
  script:
    - docker build --cache-from $CONTAINER_RELEASE_IMAGE -t $CONTAINER_TEST_IMAGE -t penpalsbackend_web .
    - docker push $CONTAINER_TEST_IMAGE

qa:
  stage: qa
  script:
    - docker-compose run -e "RAILS_ENV=test" web rails db:create
    - docker-compose run -e "RAILS_ENV=test" web rails db:migrate
    - docker-compose run -e "RAILS_ENV=test" web rspec

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
