version: '2'
services:
  web:
    build: .
    image: penpalsbackend_web
    environment:
      - RAILS_ENV=test
    command:
      - /bin/bash
      - -c
      - ./wait-for-postgres.sh postgres && rails db:create && rails db:migrate && rspec
