version: '2'
services:
  web:
    image: "registry.gitlab.nanoka.fr/penpals/backend:${CI_BUILD_REF_SLUG}"
    volumes:
      - .:/app
    links:
      - postgres
    environment:
      - RAILS_ENV=test
    command:
      - /bin/bash
      - -c
      - rails db:create && rails db:migrate && rspec
