version: '2'
services:
  web:
    build: .
    image: penpalsbackend_web
    volumes:
      - .:/app
    links:
      - postgres
    environment:
      - RAILS_ENV=test
    command:
      - /bin/bash
      - -c
      - rails db:create && rails db:migrate && rspec
