version: '2'
services:
  web:
    build: .
    image: penpalsbackend_web
    command:
      - ./wait-for-postgres.sh postgres
      - bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    volumes:
      - .:/app
    links:
      - postgres

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=SecurePasswordPG
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql/data
