version: '2'
services:
  web:
    build: .
    image: penpalsbackend_web
    environment:
      - RAILS_ENV=test
    command:
      - /app/wait-for-postgres.sh
      - postgres

  postgres:
    environment:
      - POSTGRES_PASSWORD=SecurePasswordPG