version: '2'
services:
  web:
    build: .
    image: penpalsbackend_web
    command:
      - /app/wait-for-postgres.sh
      - postgres
      - bin/rails server --port 3000 --binding 0.0.0.0
    depends_on:
      - "postgres"
    volumes:
      - .:/app
    links:
      - postgres

  postgres:
    image: postgres:9.4
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql/data
